services:
  - type: web
    name: ai-debate-moderator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:api --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        fromSecret: GOOGLE_API_KEY